### ISSUE TITLE
A Question on Evaluation

### ISSUE THREAD

**Issue by GFENGG** [hangzhaomit/Sound-of-Pixels#5]
Hello, I am a Chinese student.
I have downloaded two solo videos（2P83WJXifEs and 3d1b4UH43-E）from 'val.csv' to evaluate the performance of the model. Finally, loss is 0.5479. The effect of each speech separation is very unsatisfactory. Why is that? hope to get your reply.

P.s. I have download the trained model weights for evaluation by:
         > ./ scripts / download_trained_model.sh
and I Evaluate the trained model performance by:
         > ./ scripts / eval_MUSIC.sh

**Comment by hangzhaomit** [comment]
You are using two videos of the same instrument I guess.

**Comment by GFENGG** [comment]
Thank you. I changed two different instruments and the effect was improved.

**Comment by avis-ma** [comment]
@GFENGG I am a Chinese student too. if you have time, could I ask some questions about this project from you ...my email is ma_shuo0323@163.com. Thank you very much....
